### ISSUE TITLE
docker 3proxy Socks5 agent cannot connect after running

### ISSUE THREAD

**Issue by pylist** [rb-dock8s/3proxy#26]
docker run --name 3proxy -d -p 3128:3128 --env PROXY_LOGIN=pr0xyUser --env PROXY_PASSWORD=passw0rd riftbit/3proxy

Error: the proxy server uses unsupported methods (0x54).

**Comment by ergoz** [comment]
Thanks for report. I will check it tomorrow or in few days.

**Comment by toien** [comment]
> docker run --name 3proxy -d -p 3128:3128 --env PROXY_LOGIN=pr0xyUser --env PROXY_PASSWORD=passw0rd riftbit/3proxy
> 
> Error: the proxy server uses unsupported methods (0x54).

3128 should be http proxy port, it works for me.

but socks proxy still not work even i publish port 1080 to host machine

**Comment by ergoz** [comment]
i cant reproduce issue
